### ISSUE TITLE
Backtesting doesn't consider RSI

### ISSUE THREAD

**Issue by EduMenges** [GimmerBot/Gimmer#127]
#### Expected Behaviour
If the "Safe mode" of the scalper strategy is active, when doing a backtest it's supossed to add the RSI indicator
#### Actual Behaviour
Backtesting only considers the bot settings and disregard the RSI. Note that while out of simulation, RSI is activated.
#### Steps to Reproduce the Problem
Activate Safe mode in any scalper strategy.
#### Specifications
 - Gimmer Version: 1.8.0
 - OS: Windows 10
 - Date: 4/6/2019

**Comment by EduMenges** [comment]
Update: even if safe mode is disabled, the live mode considers it as enabled, so the RSI works when unintended.

**Comment by Flllexa** [comment]
It was fixed

**Comment by EduMenges** [comment]
Just tested and it still doesn't consider it. Both the Enabled/Disabled options yeld the same results.
