### ISSUE TITLE
Persistant candle problem

### ISSUE THREAD

**Issue by SheMaster** [GimmerBot/Gimmer#84]
#### Specifications
 - Gimmer Version: v0.2.12
 - OS: mac os 10.13.4
 - Date: 31.5.2018
 
#### Printscreen (Case needed)
![screen shot 2018-05-31 at 20 20 53](https://user-images.githubusercontent.com/39347962/40804338-42622792-651b-11e8-9f22-48c5eeab159f.png)

**Comment by Flllexa** [comment]
This was fixed in 0.2.13 version, thanks SheMaster ;)

**Comment by modem7** [comment]
![capture](https://user-images.githubusercontent.com/4349962/40813109-1a1dda90-6531-11e8-8bab-376c93c72673.JPG)

The issue is still occurring in 0.2.13 unfortunately.
